%% AEB_Controller_build.m
% Gera AEB_Controller.slx: controlador AEB completo (MIL — Model-in-the-Loop)
%
% Implementação fiel ao código C embarcado:
%   aeb_ttc.c    — TTC = d / v_rel, d_brake = v_ego² / (2 × DECEL_L3)
%   aeb_fsm.c    — FSM 7 estados com histerese, warning_min, post-brake
%   aeb_pid.c    — PI Kp=10, Ki=0.05, anti-windup [0,50], jerk limit 100 m/s³
%   aeb_alert.c  — mapeamento estado → alertas visuais/sonoros
%
% Subsistemas:
%   TTC_Calc       — cálculo de TTC e d_brake
%   Driver_Override — detecção de intervenção do motorista
%   AEB_FSM        — FSM completa (7 estados, timers, histerese)
%   PID_Brake      — controlador PI + limitação de jerk
%   Alert_Logic    — geração de alertas (CAN 0x300)
%
% Requisitos: MATLAB R2025b + Simulink

clear; close all; clc;

%% ── 0. Setup ─────────────────────────────────────────────────────────────────
script_dir = fileparts(mfilename('fullpath'));
mdl = 'AEB_Controller';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl); open_system(mdl);
sys = mdl;

set_param(sys, ...
    'Solver','ode4','SolverType','Fixed-step','FixedStep','0.001',...
    'StartTime','0','StopTime','10',...
    'SignalLogging','on','SignalLoggingName','logsout');

%% ── 1. Cenário padrão CCRs 50 km/h ──────────────────────────────────────────
% Gera os sinais de entrada pre-computando a física do evento CCRs.
% O controlador reproduzirá exatamente estas transições de estado.
DT   = 0.001;
TEND = 10.0;
t    = (0:DT:TEND)';
N    = length(t);

% ── Parâmetros (aeb_config.h) ──────────────────────────────────────────────
TTC_W=4.0; TTC_L1=3.0; TTC_L2=2.2; TTC_L3=1.8;
D_L1=20.0; D_L2=10.0; D_L3=5.0;
DECEL_L1=2.0; DECEL_L2=4.0; DECEL_L3=6.0;
V_MIN=1.39;  V_MAX=16.67;
DECEL_MAX=10.0;
WARN_MIN=0.8;  % aviso mínimo antes de frear (s)
HYST=0.2;      % histerese de desescalada (s)
POST=2.0;      % duração POST_BRAKE (s)

% ── Integração física do cenário ──────────────────────────────────────────
v_ego   = zeros(N,1);  v_ego(1)   = 13.89;  % 50 km/h
d_tgt   = zeros(N,1);  d_tgt(1)   = 50.0;   % distância inicial ao alvo
v_tgt   = zeros(N,1);                        % alvo parado
a_ego   = zeros(N,1);
v_ego_ref = zeros(N,1);  % velocidade do alvo para v_rel

% FSM simplificada para pré-computação
st=1; state_t=0; warn_acc=0; deb_t=0; pb_t=0;
decel_map = [0,0,0,DECEL_L1,DECEL_L2,DECEL_L3,0];

for i = 2:N
    vp = v_ego(i-1); dp = d_tgt(i-1); vt = v_tgt(i-1);
    v_rel_p = vp - vt;

    % TTC e d_brake
    if v_rel_p > 0.5
        ttc_p = min(dp / v_rel_p, 10);
    else
        ttc_p = 10;
    end
    d_brake_p = vp^2 / (2*DECEL_L3);
    is_cl = double(v_rel_p > 0);

    % Desired state
    if ~is_cl
        des = 1;
    elseif ttc_p <= TTC_L3 || d_brake_p >= dp
        des = 5;
    elseif ttc_p <= TTC_L2
        des = 4;
    elseif ttc_p <= TTC_L1 || dp <= D_L1
        des = 3;
    elseif ttc_p <= TTC_W
        des = 2;
    else
        des = 1;
    end
    % Distance floor
    if is_cl
        if dp <= D_L3 && des < 5, des = 5; end
        if dp <= D_L2 && des < 4, des = 4; end
        if dp <= D_L1 && des < 3, des = 3; end
    end

    % FSM transitions
    state_t = state_t + DT;
    if st == 6  % POST_BRAKE
        pb_t = pb_t + DT;
        if pb_t >= POST, st=1; pb_t=0; state_t=0; end
    elseif des > st
        if des >= 2 && st == 1
            st = 2; state_t=0; warn_acc=0; % entrar sempre em WARNING primeiro
        elseif st == 2 && warn_acc >= WARN_MIN
            st = des; state_t=0;
        end
    elseif des < st
        deb_t = deb_t + DT;
        if deb_t >= HYST
            if st >= 3
                if des >= 3, st=des;
                else, st=6; pb_t=0; end
            else
                st = des;
            end
            deb_t=0; state_t=0;
        end
    else
        deb_t = 0;
    end
    if st == 2, warn_acc = warn_acc + DT; end

    % Deceleration and kinematics
    decel = decel_map(st+1);
    a_ego(i) = -decel;
    v_ego(i) = max(0, vp - decel*DT);
    if v_ego(i) < 0.01, st=6; pb_t=0; state_t=0; end  % parou: POST_BRAKE
    d_tgt(i) = max(0.5, dp - vp*DT);
    v_tgt(i) = 0;  % alvo parado
end

v_rel    = max(0, v_ego - v_tgt);
ttc_ws   = zeros(N,1);
d_brake  = v_ego.^2 / (2*DECEL_L3);
for i=1:N
    vr = v_rel(i);
    if vr > 0.5, ttc_ws(i) = min(d_tgt(i)/vr, 10);
    else,        ttc_ws(i) = 10; end
end

% Confiança, habilitação, override
confidence   = 15*ones(N,1);
aeb_enabled  = ones(N,1);
steer_angle  = zeros(N,1);
brake_pedal  = zeros(N,1);

% Exportar workspace
ws_vars = {'t','v_ego','d_tgt','v_rel','v_tgt','a_ego','ttc_ws','d_brake',...
           'confidence','aeb_enabled','steer_angle','brake_pedal'};
for k=1:numel(ws_vars)
    vn = ws_vars{k};
    if strcmp(vn,'t'), assignin('base','t',t);
    else, assignin('base',['ws_' vn],[t, eval(vn)]); end
end

%% ── 2. Construir subsistemas ─────────────────────────────────────────────────
bld_ttc_calc(sys);
bld_driver_override(sys);
bld_aeb_fsm(sys);
bld_pid_brake(sys);
bld_alert_logic(sys);

%% ── 3. Blocos From Workspace ────────────────────────────────────────────────
fw = {
    'FW_d_tgt',     'ws_d_tgt',    [50, 80,180, 95];
    'FW_v_ego',     'ws_v_ego',    [50,110,180,125];
    'FW_v_tgt',     'ws_v_tgt',    [50,140,180,155];
    'FW_v_rel',     'ws_v_rel',    [50,170,180,185];
    'FW_a_ego',     'ws_a_ego',    [50,200,180,215];
    'FW_conf',      'ws_confidence',[50,250,180,265];
    'FW_aeb_en',    'ws_aeb_enabled',[50,280,180,295];
    'FW_steer',     'ws_steer_angle',[50,360,180,375];
    'FW_bpedal',    'ws_brake_pedal',[50,390,180,405];
};
for k=1:size(fw,1)
    add_block('simulink/Sources/From Workspace',[sys '/' fw{k,1}],...
        'VariableName',fw{k,2},'Position',fw{k,3},'Interpolate','off');
end

%% ── 4. Posicionar subsistemas ────────────────────────────────────────────────
set_param([sys '/TTC_Calc'],       'Position',[280, 80,430,170]);
set_param([sys '/Driver_Override'],'Position',[280,360,430,420]);
set_param([sys '/AEB_FSM'],        'Position',[530, 80,700,230]);
set_param([sys '/PID_Brake'],      'Position',[780, 80,940,170]);
set_param([sys '/Alert_Logic'],    'Position',[780,200,940,290]);

%% ── 5. Conexões top-level ────────────────────────────────────────────────────
% TTC_Calc ← fontes
add_line(sys,'FW_d_tgt/1',  'TTC_Calc/1','autorouting','on');
add_line(sys,'FW_v_ego/1',  'TTC_Calc/2','autorouting','on');
add_line(sys,'FW_v_tgt/1',  'TTC_Calc/3','autorouting','on');

% Driver_Override ← fontes
add_line(sys,'FW_steer/1',  'Driver_Override/1','autorouting','on');
add_line(sys,'FW_bpedal/1', 'Driver_Override/2','autorouting','on');

% AEB_FSM ← TTC_Calc + fontes + Driver_Override
add_line(sys,'TTC_Calc/1',      'AEB_FSM/1','autorouting','on');  % ttc
add_line(sys,'TTC_Calc/2',      'AEB_FSM/2','autorouting','on');  % d_brake
add_line(sys,'TTC_Calc/3',      'AEB_FSM/3','autorouting','on');  % is_closing
add_line(sys,'FW_d_tgt/1',      'AEB_FSM/4','autorouting','on');  % distance
add_line(sys,'FW_v_ego/1',      'AEB_FSM/5','autorouting','on');  % v_ego
add_line(sys,'FW_v_rel/1',      'AEB_FSM/6','autorouting','on');  % v_rel
add_line(sys,'FW_conf/1',       'AEB_FSM/7','autorouting','on');  % confidence
add_line(sys,'FW_aeb_en/1',     'AEB_FSM/8','autorouting','on');  % aeb_enabled
add_line(sys,'Driver_Override/1','AEB_FSM/9','autorouting','on'); % override

% PID_Brake ← AEB_FSM + a_ego
add_line(sys,'AEB_FSM/2',  'PID_Brake/1','autorouting','on');  % decel_target
add_line(sys,'FW_a_ego/1', 'PID_Brake/2','autorouting','on');  % a_ego (feedback)
add_line(sys,'AEB_FSM/1',  'PID_Brake/3','autorouting','on');  % fsm_state

% Alert_Logic ← AEB_FSM
add_line(sys,'AEB_FSM/1',  'Alert_Logic/1','autorouting','on'); % fsm_state

%% ── 6. To Workspace e Scope ──────────────────────────────────────────────────
tw = {
    'TW_fsm_state',    'fsm_state',    [1100, 70,1200, 85],  'AEB_FSM/1';
    'TW_decel_tgt',    'decel_target', [1100,100,1200,115],  'AEB_FSM/2';
    'TW_brake_active', 'brake_active', [1100,130,1200,145],  'AEB_FSM/3';
    'TW_alert_level',  'alert_level',  [1100,160,1200,175],  'AEB_FSM/4';
    'TW_warn_timer',   'warn_timer',   [1100,190,1200,205],  'AEB_FSM/5';
    'TW_state_timer',  'state_timer',  [1100,220,1200,235],  'AEB_FSM/6';
    'TW_brake_pct',    'brake_pct',    [1100,280,1200,295],  'PID_Brake/1';
    'TW_brake_bar',    'brake_bar',    [1100,310,1200,325],  'PID_Brake/2';
    'TW_ttc_out',      'ttc_out',      [1100,370,1200,385],  'TTC_Calc/1';
    'TW_d_brake_out',  'd_brake_out',  [1100,400,1200,415],  'TTC_Calc/2';
    'TW_is_closing',   'is_closing',   [1100,430,1200,445],  'TTC_Calc/3';
    'TW_alert_type',   'alert_type',   [1100,490,1200,505],  'Alert_Logic/1';
    'TW_alert_active', 'alert_active', [1100,520,1200,535],  'Alert_Logic/2';
    'TW_buzzer',       'buzzer_cmd',   [1100,550,1200,565],  'Alert_Logic/3';
    'TW_override',     'override_out', [1100,610,1200,625],  'Driver_Override/1';
};
for k=1:size(tw,1)
    blk = [sys '/' tw{k,1}];
    add_block('simulink/Sinks/To Workspace',blk,...
        'VariableName',tw{k,2},'SaveFormat','Array','Position',tw{k,3});
    add_line(sys,tw{k,4},[tw{k,1} '/1'],'autorouting','on');
end

% Scope (FSM state + brake pressure + TTC)
add_block('simulink/Sinks/Scope',[sys '/Scope_AEB'],...
    'NumInputPorts','4','Position',[1100,650,1180,730]);
add_line(sys,'AEB_FSM/1',  'Scope_AEB/1','autorouting','on');
add_line(sys,'PID_Brake/2','Scope_AEB/2','autorouting','on');
add_line(sys,'TTC_Calc/1', 'Scope_AEB/3','autorouting','on');
add_line(sys,'AEB_FSM/5',  'Scope_AEB/4','autorouting','on');

%% ── 7. Auto-layout e salvamento ──────────────────────────────────────────────
Simulink.BlockDiagram.arrangeSystem(sys,'FullLayout','on');
lns = find_system(sys,'FindAll','on','type','line');
if ~isempty(lns), Simulink.BlockDiagram.routeLine(lns); end

save_system(mdl, fullfile(script_dir,[mdl '.slx']));
fprintf('\n=== AEB_Controller.slx salvo em: %s ===\n\n', script_dir);
fprintf('Uso:\n');
fprintf('  sim(''AEB_Controller'')                    — CCRs 50 km/h\n');
fprintf('  AEB_Controller_scenarios(''ccrs_30'')      — 30 km/h\n');
fprintf('  AEB_Controller_scenarios(''ccrm'')         — alvo em movimento\n');
fprintf('  AEB_Controller_scenarios(''override'')     — override do motorista\n');
fprintf('  AEB_Controller_scenarios(''fault_sensor'') — falha de sensor\n');
fprintf('  AEB_Controller_plot                       — plotar resultados\n\n');

%% ══════════════════════════════════════════════════════════════════════════════
%% Funções locais
%% ══════════════════════════════════════════════════════════════════════════════

function bld_ttc_calc(sys)
%BLD_TTC_CALC  TTC_Calc: TTC, d_brake, is_closing (fiel a aeb_ttc.c)
% Entradas: distance(1), v_ego(2), v_target(3)
% Saídas:   ttc(1), d_brake(2), is_closing(3)
    p = [sys '/TTC_Calc'];
    add_block('built-in/Subsystem', p);
    del_defaults(p);
    in_names = {'distance','v_ego','v_target'};
    for k=1:3
        add_block('built-in/Inport',[p '/' in_names{k}],'Port',num2str(k),...
            'Position',[30,40+60*(k-1),60,55+60*(k-1)]);
    end
    add_block('simulink/User-Defined Functions/MATLAB Function',[p '/TTC_Logic'],...
        'Position',[120,20,280,210]);
    out_names = {'ttc','d_brake','is_closing'};
    for k=1:3
        add_block('built-in/Outport',[p '/' out_names{k}],'Port',num2str(k),...
            'Position',[380,40+50*(k-1),410,55+50*(k-1)]);
    end
    for k=1:3
        add_line(p,[in_names{k} '/1'],['TTC_Logic/' num2str(k)],'autorouting','on');
        add_line(p,['TTC_Logic/' num2str(k)],[out_names{k} '/1'],'autorouting','on');
    end
    code = [...
        'function [ttc, d_brake, is_closing] = TTC_Logic(distance, v_ego, v_target)\n'...
        '%% TTC e distancia de frenagem — fiel a aeb_ttc.c\n'...
        '%% v_rel = v_ego - v_target (positivo = fechando)\n'...
        '%% TTC = distance / v_rel  se v_rel > V_REL_MIN = 0.5 m/s\n'...
        '%% d_brake = v_ego^2 / (2 * DECEL_L3)  (distancia minima de parada)\n'...
        'V_REL_MIN = 0.5; TTC_MAX = 10.0; DECEL_L3 = 6.0;\n'...
        '\n'...
        'v_rel = v_ego - v_target;\n'...
        '\n'...
        'is_closing = double(v_rel > 0);\n'...
        '\n'...
        'if v_rel > V_REL_MIN\n'...
        '    ttc = distance / v_rel;\n'...
        '    ttc = max(0, min(ttc, TTC_MAX));\n'...
        'else\n'...
        '    ttc = TTC_MAX;\n'...
        'end\n'...
        '\n'...
        '%% Distancia minima de parada: d_brake = v_ego^2 / (2 * DECEL_L3)\n'...
        '%% Usada como floor de escalada: se d_brake >= distance -> BRAKE_L3\n'...
        'd_brake = (v_ego * v_ego) / (2.0 * DECEL_L3);\n'...
    ];
    set_mlfn_code(p,'TTC_Logic',code);
end

function bld_driver_override(sys)
%BLD_DRIVER_OVERRIDE  Detecção de intervenção do motorista (aeb_fsm.c)
% Entradas: steering_angle(1), brake_pedal(2)
% Saídas:   override_active(1)
    p = [sys '/Driver_Override'];
    add_block('built-in/Subsystem', p);
    del_defaults(p);
    in_names = {'steering_angle','brake_pedal'};
    for k=1:2
        add_block('built-in/Inport',[p '/' in_names{k}],'Port',num2str(k),...
            'Position',[30,40+60*(k-1),60,55+60*(k-1)]);
    end
    add_block('simulink/User-Defined Functions/MATLAB Function',[p '/Override_Det'],...
        'Position',[120,20,280,140]);
    add_block('built-in/Outport',[p '/override_active'],'Port','1',...
        'Position',[380,55,410,70]);
    add_line(p,'steering_angle/1','Override_Det/1','autorouting','on');
    add_line(p,'brake_pedal/1',   'Override_Det/2','autorouting','on');
    add_line(p,'Override_Det/1',  'override_active/1','autorouting','on');
    code = [...
        'function [override_active] = Override_Det(steering_angle, brake_pedal)\n'...
        '%% Detecta override do motorista — aeb_fsm.c driver_override()\n'...
        '%% brake_pedal != 0 OU abs(steering_angle) > STEERING_OVERRIDE_DEG = 5 graus\n'...
        'STEER_THR = 5.0;\n'...
        'override_active = double(brake_pedal ~= 0 || abs(steering_angle) > STEER_THR);\n'...
    ];
    set_mlfn_code(p,'Override_Det',code);
end

function bld_aeb_fsm(sys)
%BLD_AEB_FSM  FSM completa do AEB — fiel a aeb_fsm.c
% Entradas: ttc(1), d_brake(2), is_closing(3), distance(4), v_ego(5),
%           v_rel(6), confidence(7), aeb_enabled(8), override(9)
% Saídas:   fsm_state(1), decel_target(2), brake_active(3), alert_level(4),
%           warn_timer(5), state_timer(6)
    p = [sys '/AEB_FSM'];
    add_block('built-in/Subsystem', p);
    del_defaults(p);
    in_names = {'ttc','d_brake','is_closing','distance','v_ego',...
                'v_rel','confidence','aeb_enabled','override'};
    for k=1:9
        add_block('built-in/Inport',[p '/' in_names{k}],'Port',num2str(k),...
            'Position',[30,30+50*(k-1),60,45+50*(k-1)]);
    end
    add_block('simulink/User-Defined Functions/MATLAB Function',[p '/FSM_Logic'],...
        'Position',[130,150,330,580]);
    out_names = {'fsm_state','decel_target','brake_active','alert_level',...
                 'warn_timer','state_timer'};
    for k=1:6
        add_block('built-in/Outport',[p '/' out_names{k}],'Port',num2str(k),...
            'Position',[420,35+50*(k-1),450,50+50*(k-1)]);
    end
    for k=1:9
        add_line(p,[in_names{k} '/1'],['FSM_Logic/' num2str(k)],'autorouting','on');
    end
    for k=1:6
        add_line(p,['FSM_Logic/' num2str(k)],[out_names{k} '/1'],'autorouting','on');
    end
    code = [...
        'function [fsm_state, decel_target, brake_active, alert_level, warn_timer, state_timer] = ...\n'...
        '    FSM_Logic(ttc, d_brake, is_closing, distance, v_ego, v_rel, confidence, aeb_en, override)\n'...
        '%% AEB FSM — fiel a aeb_fsm.c\n'...
        '%% Estados: 0=OFF, 1=STANDBY, 2=WARNING, 3=BRAKE_L1, 4=BRAKE_L2, 5=BRAKE_L3, 6=POST_BRAKE\n'...
        '%% Parametros (aeb_config.h):\n'...
        '%%   TTC: 4.0/3.0/2.2/1.8 s  |  D_floor: 20/10/5 m\n'...
        '%%   Histerese: 0.2s (200 ciclos) | Warning_min: 0.8s | Post_brake: 2.0s\n'...
        'persistent st st_t warn_acc deb_t pb_t;\n'...
        'if isempty(st), st=1; st_t=0; warn_acc=0; deb_t=0; pb_t=0; end\n'...
        '\n'...
        'DT=0.001; TTC_W=4.0; TTC_L1=3.0; TTC_L2=2.2; TTC_L3=1.8;\n'...
        'D_L1=20.0; D_L2=10.0; D_L3=5.0;\n'...
        'V_MIN=1.39; V_MAX=16.67;\n'...
        'HYST=0.2; WARN_MIN=0.8; POST=2.0;\n'...
        'DEC=[0,0,0,2.0,4.0,6.0,6.0];  %% decel por estado (POST_BRAKE mantém L3)\n'...
        '\n'...
        'st_t = st_t + DT;\n'...
        '\n'...
        '%% --- Prioridade 1: falha de sensor -> OFF -------------------------\n'...
        'if confidence < 1\n'...
        '    st=0; st_t=0; warn_acc=0; deb_t=0;\n'...
        '    fsm_state=0; decel_target=0; brake_active=0; alert_level=0;\n'...
        '    warn_timer=0; state_timer=0;\n'...
        '    return;\n'...
        'end\n'...
        '\n'...
        '%% --- Prioridade 2: AEB desabilitado -> OFF ------------------------\n'...
        'if ~aeb_en\n'...
        '    st=0; st_t=0;\n'...
        '    fsm_state=0; decel_target=0; brake_active=0; alert_level=0;\n'...
        '    warn_timer=warn_acc; state_timer=st_t;\n'...
        '    return;\n'...
        'end\n'...
        '\n'...
        '%% --- Prioridade 3: velocidade fora da janela valida ---------------\n'...
        'out_of_range = (v_ego < V_MIN) || (v_ego > V_MAX);\n'...
        'if out_of_range\n'...
        '    %% Excecao 1: carro parou durante frenagem -> POST_BRAKE\n'...
        '    if v_ego < 0.01 && st >= 3\n'...
        '        st=6; st_t=0; pb_t=0;\n'...
        '    %% Excecao 2: distancia critica ainda fechando -> manter floor\n'...
        '    elseif distance <= D_L1 && v_rel > 0\n'...
        '        min_st = 3;\n'...
        '        if distance <= D_L3, min_st=5;\n'...
        '        elseif distance <= D_L2, min_st=4; end\n'...
        '        if st < min_st, st=min_st; st_t=0; end\n'...
        '    else\n'...
        '        st=1; st_t=0; warn_acc=0; deb_t=0;\n'...
        '    end\n'...
        '    fsm_state=double(st); decel_target=DEC(st+1);\n'...
        '    brake_active=double(st>=3); warn_timer=warn_acc; state_timer=st_t;\n'...
        '    alert_level = get_alert(st);\n'...
        '    return;\n'...
        'end\n'...
        '\n'...
        '%% --- Prioridade 4: override do motorista durante frenagem ---------\n'...
        'if override && st >= 2\n'...
        '    st=1; st_t=0; warn_acc=0; deb_t=0;\n'...
        '    fsm_state=1; decel_target=0; brake_active=0;\n'...
        '    warn_timer=0; state_timer=0; alert_level=0;\n'...
        '    return;\n'...
        'end\n'...
        '\n'...
        '%% --- Calcular estado desejado (evaluate_threat) -------------------\n'...
        'if ~is_closing\n'...
        '    des = 1;\n'...
        'elseif ttc <= TTC_L3 || d_brake >= distance\n'...
        '    des = 5;  %% d_brake >= distance: nao consegue parar\n'...
        'elseif ttc <= TTC_L2\n'...
        '    des = 4;\n'...
        'elseif ttc <= TTC_L1\n'...
        '    des = 3;\n'...
        'elseif ttc <= TTC_W\n'...
        '    des = 2;\n'...
        'else\n'...
        '    des = 1;\n'...
        'end\n'...
        '%% Distance floor (is_closing=true)\n'...
        'if is_closing\n'...
        '    if distance <= D_L3 && des < 5, des=5; end\n'...
        '    if distance <= D_L2 && des < 4, des=4; end\n'...
        '    if distance <= D_L1 && des < 3, des=3; end\n'...
        'end\n'...
        '\n'...
        '%% --- Logica de transicao por estado --------------------------------\n'...
        'if st == 6  %% POST_BRAKE: aguardar 2s\n'...
        '    pb_t = pb_t + DT;\n'...
        '    if pb_t >= POST, st=1; st_t=0; warn_acc=0; pb_t=0; end\n'...
        '\n'...
        'elseif st == 0  %% OFF: retornar a STANDBY\n'...
        '    st=1; st_t=0;\n'...
        '\n'...
        'elseif st == 1  %% STANDBY\n'...
        '    warn_acc=0; deb_t=0;\n'...
        '    if des >= 2  %% qualquer ameaca: ir para WARNING\n'...
        '        st=2; st_t=0; warn_acc=0;\n'...
        '    end\n'...
        '\n'...
        'elseif st == 2  %% WARNING\n'...
        '    warn_acc = warn_acc + DT;\n'...
        '    if des == 1\n'...
        '        deb_t = deb_t + DT;\n'...
        '        if deb_t >= HYST, st=1; st_t=0; warn_acc=0; deb_t=0; end\n'...
        '    else\n'...
        '        deb_t = 0;\n'...
        '        if warn_acc >= WARN_MIN && des >= 3  %% minimo 0.8s de aviso\n'...
        '            st=des; st_t=0;\n'...
        '        end\n'...
        '    end\n'...
        '\n'...
        'elseif st == 3  %% BRAKE_L1\n'...
        '    if v_ego < 0.01, st=6; st_t=0; pb_t=0;\n'...
        '    elseif des > st, st=des; st_t=0; deb_t=0;\n'...
        '    elseif des < st\n'...
        '        deb_t = deb_t + DT;\n'...
        '        if deb_t >= HYST\n'...
        '            if des < 3, st=6; pb_t=0; else, st=des; end\n'...
        '            st_t=0; deb_t=0; warn_acc=0;\n'...
        '        end\n'...
        '    else, deb_t=0;\n'...
        '    end\n'...
        '\n'...
        'elseif st == 4  %% BRAKE_L2\n'...
        '    if v_ego < 0.01, st=6; st_t=0; pb_t=0;\n'...
        '    elseif des == 5, st=5; st_t=0; deb_t=0;\n'...
        '    elseif des < st\n'...
        '        deb_t = deb_t + DT;\n'...
        '        if deb_t >= HYST\n'...
        '            if des >= 3, st=3; else, st=6; pb_t=0; end\n'...
        '            st_t=0; deb_t=0;\n'...
        '        end\n'...
        '    else, deb_t=0;\n'...
        '    end\n'...
        '\n'...
        'elseif st == 5  %% BRAKE_L3\n'...
        '    if v_ego < 0.01, st=6; st_t=0; pb_t=0;\n'...
        '    elseif des < st\n'...
        '        deb_t = deb_t + DT;\n'...
        '        if deb_t >= HYST\n'...
        '            if des >= 3, st=des; else, st=6; pb_t=0; end\n'...
        '            st_t=0; deb_t=0;\n'...
        '        end\n'...
        '    else, deb_t=0;\n'...
        '    end\n'...
        'end\n'...
        '\n'...
        '%% --- Saidas -------------------------------------------------------\n'...
        'fsm_state    = double(st);\n'...
        'decel_target = DEC(st+1);\n'...
        'brake_active = double(st >= 3);\n'...
        'alert_level  = get_alert(st);\n'...
        'warn_timer   = warn_acc;\n'...
        'state_timer  = st_t;\n'...
        '\n'...
        '%%--- Funcao auxiliar -----------------------------------------------\n'...
        'function lv = get_alert(s)\n'...
        '    if s <= 1 || s == 6, lv = double(s == 6);  %% POST_BRAKE: level 0\n'...
        '    elseif s == 2,       lv = 1;\n'...
        '    elseif s == 3,       lv = 2;\n'...
        '    else                 lv = 3;\n'...
        '    end\n'...
        'end\n'...
    ];
    set_mlfn_code(p,'FSM_Logic',code);
end

function bld_pid_brake(sys)
%BLD_PID_BRAKE  Controlador PI de freio — fiel a aeb_pid.c
% Kp=10.0, Ki=0.05, anti-windup integ [0,50]%
% Jerk limit: 100 m/s³ → max_delta = (100 * 100/10) * 0.001 = 1.0 %/step
% Entradas: decel_target(1), a_ego(2), fsm_state(3)
% Saídas:   brake_pct(1) [0-100%], brake_bar(2) [0-10 bar]
    p = [sys '/PID_Brake'];
    add_block('built-in/Subsystem', p);
    del_defaults(p);
    in_names = {'decel_target','a_ego','fsm_state'};
    for k=1:3
        add_block('built-in/Inport',[p '/' in_names{k}],'Port',num2str(k),...
            'Position',[30,40+60*(k-1),60,55+60*(k-1)]);
    end
    add_block('simulink/User-Defined Functions/MATLAB Function',[p '/PID_Logic'],...
        'Position',[120,20,280,220]);
    out_names = {'brake_pct','brake_bar'};
    for k=1:2
        add_block('built-in/Outport',[p '/' out_names{k}],'Port',num2str(k),...
            'Position',[380,40+60*(k-1),410,55+60*(k-1)]);
    end
    for k=1:3
        add_line(p,[in_names{k} '/1'],['PID_Logic/' num2str(k)],'autorouting','on');
    end
    for k=1:2
        add_line(p,['PID_Logic/' num2str(k)],[out_names{k} '/1'],'autorouting','on');
    end
    code = [...
        'function [brake_pct, brake_bar] = PID_Logic(decel_target, a_ego, fsm_state)\n'...
        '%% Controlador PI de freio — fiel a aeb_pid.c\n'...
        '%%   Kp=10.0, Ki=0.05 (aeb_config.h)\n'...
        '%%   Anti-windup: integral em [0, 50] %\n'...
        '%%   Output: [0, 100] %  —  convertido para bar via /10\n'...
        '%%   Jerk limit: MAX_JERK=100 m/s³ → max_delta = (100 * 100/10) * 0.001 = 1.0 %/ciclo\n'...
        'persistent integ prev_out;\n'...
        'if isempty(integ), integ=0; prev_out=0; end\n'...
        '\n'...
        'KP=10.0; KI=0.05; DT=0.001;\n'...
        'INTEG_MAX=50.0; OUT_MAX=100.0; OUT_MIN=0.0;\n'...
        'BRAKE_MAX_DECEL=10.0; MAX_JERK=100.0;\n'...
        'max_delta = (MAX_JERK * (OUT_MAX / BRAKE_MAX_DECEL)) * DT;  %% 1.0 %/ciclo\n'...
        '\n'...
        'if decel_target <= 0 || fsm_state < 3\n'...
        '    integ=0; prev_out=0;\n'...
        '    brake_pct=0; brake_bar=0;\n'...
        '    return;\n'...
        'end\n'...
        '\n'...
        '%% Feedback: actual_decel = -a_ego (positivo quando desacelerando)\n'...
        'actual_decel = -a_ego;\n'...
        '\n'...
        '%% Erro: positivo quando falta desaceleracao\n'...
        'err = decel_target - actual_decel;\n'...
        '\n'...
        '%% Termo proporcional\n'...
        'p_term = KP * err;\n'...
        '\n'...
        '%% Integral com anti-windup por clamping [0, 50] %\n'...
        'integ = integ + KI * err * DT;\n'...
        'integ = max(0, min(INTEG_MAX, integ));\n'...
        '\n'...
        '%% Saida PI bruta\n'...
        'raw = p_term + integ;\n'...
        'raw = max(OUT_MIN, min(OUT_MAX, raw));\n'...
        '\n'...
        '%% Limitacao de jerk: max_delta = 1.0 %/ciclo\n'...
        'delta = raw - prev_out;\n'...
        'delta = max(-max_delta, min(max_delta, delta));\n'...
        'brake_pct = max(OUT_MIN, min(OUT_MAX, prev_out + delta));\n'...
        'prev_out = brake_pct;\n'...
        '\n'...
        '%% Converter para bar: 100% -> 10 bar\n'...
        'brake_bar = brake_pct * 0.1;\n'...
    ];
    set_mlfn_code(p,'PID_Logic',code);
end

function bld_alert_logic(sys)
%BLD_ALERT_LOGIC  Geração de alertas — fiel a aeb_alert.c
% Entrada:  fsm_state(1)
% Saídas:   alert_type(1), alert_active(2), buzzer_cmd(3)
    p = [sys '/Alert_Logic'];
    add_block('built-in/Subsystem', p);
    del_defaults(p);
    add_block('built-in/Inport',[p '/fsm_state'],'Port','1',...
        'Position',[30,55,60,70]);
    add_block('simulink/User-Defined Functions/MATLAB Function',[p '/Alert_Map'],...
        'Position',[120,20,280,200]);
    out_names = {'alert_type','alert_active','buzzer_cmd'};
    for k=1:3
        add_block('built-in/Outport',[p '/' out_names{k}],'Port',num2str(k),...
            'Position',[380,35+55*(k-1),410,50+55*(k-1)]);
    end
    add_line(p,'fsm_state/1','Alert_Map/1','autorouting','on');
    for k=1:3
        add_line(p,['Alert_Map/' num2str(k)],[out_names{k} '/1'],'autorouting','on');
    end
    code = [...
        'function [alert_type, alert_active, buzzer_cmd] = Alert_Map(fsm_state)\n'...
        '%% Mapeamento FSM -> alertas — fiel a aeb_alert.c + DBC VAL_ AEB_Alert\n'...
        '%% AlertType: 0=NONE, 1=VISUAL, 2=AUDIBLE, 3=BOTH\n'...
        '%% BuzzerCmd: 0=Off, 1=SingleBeep, 2=DoubleBeep, 3=ContinuousBeep, 4=FastPulse\n'...
        'st = round(fsm_state);\n'...
        'switch st\n'...
        '    case {0, 1}  %% OFF, STANDBY: silencio\n'...
        '        alert_type=0; alert_active=0; buzzer_cmd=0;\n'...
        '    case 2  %% WARNING: visual+audible, SingleBeep\n'...
        '        alert_type=3; alert_active=1; buzzer_cmd=1;\n'...
        '    case 3  %% BRAKE_L1: visual+audible, DoubleBeep\n'...
        '        alert_type=3; alert_active=1; buzzer_cmd=2;\n'...
        '    case 4  %% BRAKE_L2: visual+audible, FastPulse\n'...
        '        alert_type=3; alert_active=1; buzzer_cmd=4;\n'...
        '    case 5  %% BRAKE_L3: visual+audible, ContinuousBeep\n'...
        '        alert_type=3; alert_active=1; buzzer_cmd=3;\n'...
        '    case 6  %% POST_BRAKE: visual apenas, Off\n'...
        '        alert_type=1; alert_active=1; buzzer_cmd=0;\n'...
        '    otherwise\n'...
        '        alert_type=0; alert_active=0; buzzer_cmd=0;\n'...
        'end\n'...
    ];
    set_mlfn_code(p,'Alert_Map',code);
end

%% ── Auxiliares ───────────────────────────────────────────────────────────────

function del_defaults(p)
    lns = find_system(p,'FindAll','on','SearchDepth',1,'type','line');
    for k=1:numel(lns), delete_line(lns(k)); end
    blks = find_system(p,'SearchDepth',1,'Type','Block');
    for k=1:numel(blks)
        if strcmp(blks{k},p), continue; end
        bt = get_param(blks{k},'BlockType');
        if any(strcmp(bt,{'Inport','Outport'})), delete_block(blks{k}); end
    end
end

function set_mlfn_code(subsys, block_name, code_str)
    full_path = [subsys '/' block_name];
    rt = sfroot();
    charts = rt.find('-isa','Stateflow.EMChart');
    chart = [];
    for k=1:numel(charts)
        if strcmp(charts(k).Path, full_path), chart = charts(k); break; end
    end
    if isempty(chart)
        warning('MATLAB Function nao encontrado: %s', full_path); return;
    end
    chart.Script = sprintf(code_str);
end
