%% AEB_UDS_build.m
% Gera AEB_UDS.slx: camada de diagnóstico UDS (ISO 14229) do sistema AEB
%
% Serviços UDS implementados:
%   0x10 — DiagnosticSessionControl (Default / Extended / Programming)
%   0x11 — ECUReset
%   0x14 — ClearDiagnosticInformation
%   0x19 — ReadDTCInformation (subfunção 0x02 — reportDTCByStatusMask)
%   0x22 — ReadDataByIdentifier  (DIDs F100-F103)
%   0x27 — SecurityAccess — LFSR-32 seed + algoritmo seed-key
%   0x2E — WriteDataByIdentifier (DIDs F200-F202) — requer desbloqueio
%   0x31 — RoutineControl (0x0301 enable/disable AEB, 0x0302 self-test)
%   0x3E — TesterPresent (suprime timeout S3)
%
% DTCs modelados (7):
%   C1001 Radar timeout    C1002 Lidar timeout     C1003 Plausibilidade
%   C1004 CRC error        C1005 Alive stuck        C1006 Falha atuador
%   C1007 Sobre-temperatura
%
% Criptografia (SID 0x27):
%   Semente: LFSR Galois 32 bits (polinômio 0x80200003)
%   Chave: key = ROTL32(seed ^ 0xA55A3CC3, 7) + 0x12345678  (mod 2^32)
%
% Requisitos: MATLAB R2025b + Simulink

clear; close all; clc;

%% ── 0. Setup ─────────────────────────────────────────────────────────────────
script_dir = fileparts(mfilename('fullpath'));
mdl = 'AEB_UDS';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl); open_system(mdl);
sys = mdl;

set_param(sys, ...
    'Solver','ode4','SolverType','Fixed-step','FixedStep','0.1',...
    'StartTime','0','StopTime','30',...
    'SignalLogging','on','SignalLoggingName','logsout');

%% ── 1. Cenário nominal: pré-computa entradas para 30 s @ 100 ms ──────────────
DT   = 0.1;
TEND = 30.0;
t    = (0:DT:TEND)';
N    = length(t);

% ── Sinais de sistema (saídas do controlador / percepção) ──────────────────
ttc_in      = 10 * ones(N,1);           % TTC (s)
fsm_in      = ones(N,1);                % FSM state (1=STANDBY)
brake_bar   = zeros(N,1);               % Pressão de freio (bar)
sens_fault  = zeros(N,1);               % Falha sensor percepção
crc_err     = zeros(N,1);               % Erro CRC CAN
alive_err   = zeros(N,1);               % Alive counter travado
timeout_err = zeros(N,1);               % Timeout CAN
act_err     = zeros(N,1);               % Falha atuador (pressão ≠ comandada)
ecu_temp    = 25 * ones(N,1);           % Temperatura ECU (°C)

% ── Sequência de requisições UDS (simulação do tester externo) ────────────
% Formato: cada linha = [t_inicio, SID, B2, B3, B4, B5, B6, B7, B8]
% Padding com zeros; req_valid=1 apenas no ciclo da requisição
req_frames = [
    %  t     SID    B2    B3    B4    B5    B6    B7    B8
     1.0, 0x10, 0x03,    0,    0,    0,    0,    0,    0;  % Extended session
     2.0, 0x22, 0xF1, 0x00,    0,    0,    0,    0,    0;  % ReadDID TTC
     3.0, 0x22, 0xF1, 0x01,    0,    0,    0,    0,    0;  % ReadDID FSM state
     4.0, 0x3E, 0x00,    0,    0,    0,    0,    0,    0;  % TesterPresent
     % Falha injetada em t=5s (sensor fault → DTC C1001 confirmado em t=8s)
     8.0, 0x19, 0x02, 0xFF,    0,    0,    0,    0,    0;  % ReadDTC (all)
     % Security Access: RequestSeed
    10.0, 0x27, 0x01,    0,    0,    0,    0,    0,    0;
     % Security Access: SendKey (pré-calculado para seed=0xABCD1234)
     % key = ROTL32(0xABCD1234 ^ 0xA55A3CC3, 7) + 0x12345678
     % seed ^ mask = 0xABCD1234 ^ 0xA55A3CC3 = 0x0E972EF7
     % ROTL32(0x0E972EF7, 7) = 0x74B97F87 (aprox — calculado abaixo)
     % valor correto preenchido pelo cenário
    11.0, 0x27, 0x02, 0x74, 0xB9, 0x7F, 0x87,    0,    0;  % placeholder
     % Write TTC Warning = 3.5 s (DID F200)
    12.0, 0x2E, 0xF2, 0x00, 0x40, 0x60, 0x00, 0x00,    0;  % 3.5f em IEEE-754
     % Routine: Disable AEB
    15.0, 0x31, 0x01, 0x03, 0x01,    0,    0,    0,    0;
     % Routine: Enable AEB
    20.0, 0x31, 0x01, 0x03, 0x01,    1,    0,    0,    0;  % sub=enable
     % Clear all DTCs
    25.0, 0x14, 0xFF, 0xFF, 0xFF,    0,    0,    0,    0;
     % Confirm DTCs cleared
    27.0, 0x19, 0x02, 0xFF,    0,    0,    0,    0,    0;
     % TesterPresent (keep session)
    28.0, 0x3E, 0x00,    0,    0,    0,    0,    0,    0;
];

% Calcular chave correta para seed 0xABCD1234
seed0 = uint32(0xABCD1234);
key0  = uds_compute_key(seed0);
kb = typecast(key0,'uint8');
% Atualiza linha do SendKey
idx = find(req_frames(:,1) == 11.0);
req_frames(idx, 4:7) = double(kb);

% Montar vetores de sinal
req_bytes = zeros(N, 9);   % [SID, B2..B8, valid]
req_valid = zeros(N, 1);
for r = 1:size(req_frames,1)
    k = round(req_frames(r,1) / DT) + 1;
    if k >= 1 && k <= N
        req_bytes(k,:) = req_frames(r,2:end);
        req_valid(k)   = 1;
    end
end

% ── Injeção de falhas ──────────────────────────────────────────────────────
% C1001: radar timeout t=5..25s  (dura até ClearDTC em t=25s)
timeout_err(round(5/DT)+1 : round(25/DT)) = 1;
% C1004: CRC error t=13..14s
crc_err(round(13/DT)+1 : round(14/DT)) = 1;
% C1007: over-temp t=16..19s
ecu_temp(round(16/DT)+1 : round(19/DT)) = 90;

% ── Exportar workspace ────────────────────────────────────────────────────
ws_ttc       = [t, ttc_in];
ws_fsm       = [t, fsm_in];
ws_brake_bar = [t, brake_bar];
ws_sens_f    = [t, sens_fault];
ws_crc_err   = [t, crc_err];
ws_alive_err = [t, alive_err];
ws_timeout   = [t, timeout_err];
ws_act_err   = [t, act_err];
ws_ecu_temp  = [t, ecu_temp];
ws_req_valid = [t, req_valid];

% req_bytes: 9 colunas → exporta como sinal escalar, mux de 9 canais
for col = 1:9
    assignin('base', sprintf('ws_req_b%d', col), [t, req_bytes(:,col)]);
end

vars = {'ws_ttc','ws_fsm','ws_brake_bar','ws_sens_f','ws_crc_err',...
        'ws_alive_err','ws_timeout','ws_act_err','ws_ecu_temp','ws_req_valid'};
for k = 1:numel(vars)
    assignin('base', vars{k}, eval(vars{k}));
end

fprintf('Workspace UDS configurado (%d amostras, DT=%.1f s).\n', N, DT);

%% ── 2. Criar subsistema AEB_UDS ──────────────────────────────────────────────
bld_uds_main(sys);
bld_inputs(sys);
bld_outputs(sys);
connect_model(sys);

%% ── 3. Salvar ────────────────────────────────────────────────────────────────
save_path = fullfile(script_dir, [mdl '.slx']);
save_system(mdl, save_path);
fprintf('Modelo salvo: %s\n', save_path);
fprintf('\nPara simular:\n');
fprintf('  AEB_UDS_scenarios(''dtc_lifecycle'');\n');
fprintf('  out = sim(''AEB_UDS'');\n');
fprintf('  AEB_UDS_plot(out);\n');

%% ═══════════════════════════════════════════════════════════════════════════
%% FUNÇÕES DE CONSTRUÇÃO
%% ═══════════════════════════════════════════════════════════════════════════

function bld_inputs(sys)
%% Blocos From Workspace para todas as entradas do UDS
    FW = {
        'FW_ttc',      'ws_ttc',      0, 600;
        'FW_fsm',      'ws_fsm',      0, 650;
        'FW_brake',    'ws_brake_bar',0, 700;
        'FW_sensf',    'ws_sens_f',   0, 750;
        'FW_crc',      'ws_crc_err',  0, 800;
        'FW_alive',    'ws_alive_err',0, 850;
        'FW_timeout',  'ws_timeout',  0, 900;
        'FW_act',      'ws_act_err',  0, 950;
        'FW_temp',     'ws_ecu_temp', 0, 1000;
        'FW_valid',    'ws_req_valid',0, 1050;
    };
    for r = 1:size(FW,1)
        add_block('simulink/Sources/From Workspace',...
            [sys '/' FW{r,1}],...
            'VariableName', FW{r,3+1},...
            'Position', [FW{r,3}, FW{r,4}, FW{r,3}+120, FW{r,4}+30]);
    end
    for col = 1:9
        nm  = sprintf('FW_req_b%d', col);
        var = sprintf('ws_req_b%d', col);
        add_block('simulink/Sources/From Workspace',...
            [sys '/' nm],'VariableName',var,...
            'Position',[160,(1100+(col-1)*50),280,(1130+(col-1)*50)]);
    end
end

function bld_uds_main(sys)
%% Subsistema principal: AEB_UDS_Handler
    sub = [sys '/AEB_UDS_Handler'];
    add_block('built-in/Subsystem', sub, 'Position',[400,400,700,900]);

    % ── Adicionar MATLAB Function block ──────────────────────────────────
    mf = [sub '/uds_handler'];
    add_block('simulink/User-Defined Functions/MATLAB Function', mf,...
              'Position',[80,80,400,600]);

    % Código injetado via Stateflow API
    sf = sfroot();
    chart = sf.find('-isa','Stateflow.EMChart','Path',[sub '/uds_handler']);
    if ~isempty(chart)
        chart.Script = uds_handler_code();
    end

    % ── Portas do subsistema ──────────────────────────────────────────────
    inputs = {'ttc','fsm_state','brake_bar','sens_fault','crc_err',...
              'alive_err','timeout_err','act_err','ecu_temp',...
              'req_valid','b1','b2','b3','b4','b5','b6','b7','b8','b9'};
    for k = 1:numel(inputs)
        add_block('simulink/Ports & Subsystems/In1',...
            [sub '/In_' inputs{k}],...
            'Position',[20,50+k*40,50,70+k*40]);
    end

    outputs = {'resp_b1','resp_b2','resp_b3','resp_b4','resp_b5',...
               'resp_b6','resp_b7','resp_b8','resp_len',...
               'aeb_enabled','ttc_warn_cal','ttc_l1_cal','kp_cal',...
               'dtc_active','dtc_count','fault_lamp','session_state','sec_unlocked'};
    for k = 1:numel(outputs)
        add_block('simulink/Ports & Subsystems/Out1',...
            [sub '/Out_' outputs{k}],...
            'Position',[500,50+k*35,530,70+k*35]);
    end
end

function bld_outputs(sys)
%% Blocos To Workspace para sinais de saída
    sigs = {'aeb_enabled','ttc_warn_cal','ttc_l1_cal','kp_cal',...
            'dtc_active','dtc_count','fault_lamp','session_state','sec_unlocked',...
            'resp_len'};
    for k = 1:numel(sigs)
        add_block('simulink/Sinks/To Workspace',...
            [sys '/TW_' sigs{k}],...
            'VariableName', sigs{k},...
            'SaveFormat','Array',...
            'Position',[900,300+k*50,1020,320+k*50]);
    end
end

function connect_model(sys)
%% Conexões principais (entradas do workspace → subsistema → saídas)
    inputs_fw = {'FW_ttc','FW_fsm','FW_brake','FW_sensf','FW_crc',...
                 'FW_alive','FW_timeout','FW_act','FW_temp','FW_valid'};
    for k = 1:numel(inputs_fw)
        try
            add_line(sys, [inputs_fw{k} '/1'], ...
                     ['AEB_UDS_Handler/' num2str(k)], 'autorouting','on');
        catch
        end
    end
    for col = 1:9
        try
            add_line(sys, [sprintf('FW_req_b%d',col) '/1'],...
                     ['AEB_UDS_Handler/' num2str(10+col)],'autorouting','on');
        catch
        end
    end
end

%% ═══════════════════════════════════════════════════════════════════════════
%% CÓDIGO DA MATLAB FUNCTION (UDS Handler)
%% ═══════════════════════════════════════════════════════════════════════════

function code = uds_handler_code()
code = [
'function [resp_b1,resp_b2,resp_b3,resp_b4,resp_b5,resp_b6,resp_b7,resp_b8,'...
'resp_len,aeb_enabled,ttc_warn_cal,ttc_l1_cal,kp_cal,'...
'dtc_active,dtc_count,fault_lamp,session_state,sec_unlocked] = ...'...
'uds_handler(ttc,fsm_state,brake_bar,sens_fault,crc_err,'...
'alive_err,timeout_err,act_err,ecu_temp,'...
'req_valid,b1,b2,b3,b4,b5,b6,b7,b8,b9) '...
'%#codegen'...
newline ...
'%% ── Constantes ──────────────────────────────────────────────────────'...
newline ...
'DT_UDS      = 0.1;    % ciclo UDS (s)'...
newline ...
'S3_TIMEOUT  = 5.0;    % timeout sessao (s)'...
newline ...
'DEB_FAULT   = 3;      % debounce falhas de sensor (ciclos)'...
newline ...
'DEB_ALIVE   = 5;      % debounce alive counter (ciclos)'...
newline ...
'DEB_TEMP    = 3;'...
newline ...
'TEMP_MAX    = 85.0;   % temperatura critica (C)'...
newline ...
'SECRET_XOR  = uint32(hex2dec(''A55A3CC3''));'...
newline ...
'SECRET_ADD  = uint32(hex2dec(''12345678''));'...
newline ...
'SEED_INIT   = uint32(hex2dec(''ABCD1234''));'...
newline ...
'%% ── Persistent state ────────────────────────────────────────────────'...
newline ...
'persistent sess s3 seed unlocked dtc dtc_ctr ttc_w ttc_l1 kp_g aeb_en;'...
newline ...
'if isempty(sess)'...
newline ...
'    sess    = uint8(1);       % 1=default 2=extended 3=programming'...
newline ...
'    s3      = 0.0;'...
newline ...
'    seed    = SEED_INIT;'...
newline ...
'    unlocked= uint8(0);'...
newline ...
'    dtc     = zeros(1,7,''uint8'');  % confirmed DTCs (C1001..C1007)'...
newline ...
'    dtc_ctr = zeros(1,7,''uint16''); % debounce counters'...
newline ...
'    ttc_w   = 4.0;   ttc_l1 = 3.0;  kp_g = 10.0;'...
newline ...
'    aeb_en  = uint8(1);'...
newline ...
'end'...
newline ...
'%% ── DTC fault detection ──────────────────────────────────────────────'...
newline ...
'% C1001 radar timeout'...
newline ...
'fault_flags = [timeout_err, 0, 0, crc_err, alive_err, act_err, ...'...
newline ...
'               double(ecu_temp > TEMP_MAX)];'...
newline ...
'deb_lim = [DEB_FAULT,DEB_FAULT,DEB_FAULT,DEB_FAULT,DEB_ALIVE,DEB_FAULT,DEB_TEMP];'...
newline ...
'for i = 1:7'...
newline ...
'    if fault_flags(i) > 0'...
newline ...
'        dtc_ctr(i) = dtc_ctr(i) + uint16(1);'...
newline ...
'        if dtc_ctr(i) >= uint16(deb_lim(i))'...
newline ...
'            dtc(i) = uint8(1);'...
newline ...
'        end'...
newline ...
'    else'...
newline ...
'        dtc_ctr(i) = uint16(0);'...
newline ...
'    end'...
newline ...
'end'...
newline ...
'%% ── Session S3 timer ────────────────────────────────────────────────'...
newline ...
'if sess > 1'...
newline ...
'    s3 = s3 + DT_UDS;'...
newline ...
'    if s3 >= S3_TIMEOUT'...
newline ...
'        sess     = uint8(1);  % retorna a DEFAULT'...
newline ...
'        unlocked = uint8(0);'...
newline ...
'        s3       = 0.0;'...
newline ...
'    end'...
newline ...
'end'...
newline ...
'%% ── Request processing ──────────────────────────────────────────────'...
newline ...
'resp  = zeros(1,8,''uint8'');'...
newline ...
'rlen  = uint8(0);'...
newline ...
'if req_valid > 0'...
newline ...
'    req = uint8([b1,b2,b3,b4,b5,b6,b7,b8,b9]);'...
newline ...
'    SID = req(1);'...
newline ...
'    switch SID'...
newline ...
'      %% 0x10 DiagnosticSessionControl ─────────────────────────────────'...
newline ...
'      case uint8(hex2dec(''10''))'...
newline ...
'        sub = req(2);'...
newline ...
'        if sub==1 || sub==2 || sub==3'...
newline ...
'            sess     = sub;'...
newline ...
'            unlocked = uint8(0);'...
newline ...
'            s3       = 0.0;'...
newline ...
'            resp(1)  = uint8(hex2dec(''50''));  % positive 0x40+SID'...
newline ...
'            resp(2)  = sub;'...
newline ...
'            rlen     = uint8(2);'...
newline ...
'        else'...
newline ...
'            resp     = nrc(SID, uint8(hex2dec(''12'')));  % subFunctionNotSupported'...
newline ...
'            rlen     = uint8(3);'...
newline ...
'        end'...
newline ...
'      %% 0x11 ECUReset ──────────────────────────────────────────────────'...
newline ...
'      case uint8(hex2dec(''11''))'...
newline ...
'        sess     = uint8(1);'...
newline ...
'        unlocked = uint8(0);'...
newline ...
'        s3       = 0.0;'...
newline ...
'        resp(1)  = uint8(hex2dec(''51''));'...
newline ...
'        resp(2)  = req(2);'...
newline ...
'        rlen     = uint8(2);'...
newline ...
'      %% 0x22 ReadDataByIdentifier ─────────────────────────────────────'...
newline ...
'      case uint8(hex2dec(''22''))'...
newline ...
'        did = uint16(req(2))*256 + uint16(req(3));'...
newline ...
'        resp(1) = uint8(hex2dec(''62''));'...
newline ...
'        resp(2) = req(2); resp(3) = req(3);'...
newline ...
'        if did == uint16(hex2dec(''F100''))        % TTC (float32)'...
newline ...
'            fb = float2bytes(single(ttc));'...
newline ...
'            resp(4:7) = fb;  rlen = uint8(7);'...
newline ...
'        elseif did == uint16(hex2dec(''F101''))    % FSM state (uint8)'...
newline ...
'            resp(4) = uint8(fsm_state);  rlen = uint8(4);'...
newline ...
'        elseif did == uint16(hex2dec(''F102''))    % brake_bar (float32)'...
newline ...
'            fb = float2bytes(single(brake_bar));'...
newline ...
'            resp(4:7) = fb;  rlen = uint8(7);'...
newline ...
'        elseif did == uint16(hex2dec(''F103''))    % fault counter (uint8)'...
newline ...
'            resp(4) = uint8(sum(dtc));   rlen = uint8(4);'...
newline ...
'        else'...
newline ...
'            resp = nrc(SID, uint8(hex2dec(''31'')));  % requestOutOfRange'...
newline ...
'            rlen = uint8(3);'...
newline ...
'        end'...
newline ...
'      %% 0x27 SecurityAccess ────────────────────────────────────────────'...
newline ...
'      case uint8(hex2dec(''27''))'...
newline ...
'        sub = req(2);'...
newline ...
'        if sess < 2  % requer sessao Extended ou Programming'...
newline ...
'            resp = nrc(SID, uint8(hex2dec(''22'')));  % conditionsNotCorrect'...
newline ...
'            rlen = uint8(3);'...
newline ...
'        elseif sub == uint8(1)  % RequestSeed'...
newline ...
'            seed = lfsr32(seed);'...
newline ...
'            sb   = typecast(seed, ''uint8'');'...
newline ...
'            resp(1) = uint8(hex2dec(''67''));'...
newline ...
'            resp(2) = uint8(1);'...
newline ...
'            resp(3:6) = sb;'...
newline ...
'            rlen = uint8(6);'...
newline ...
'            unlocked = uint8(0);  % nova semente invalida chave anterior'...
newline ...
'        elseif sub == uint8(2)  % SendKey'...
newline ...
'            recv_key = typecast(req(3:6), ''uint32'');'...
newline ...
'            exp_key  = compute_key(seed, SECRET_XOR, SECRET_ADD);'...
newline ...
'            if recv_key == exp_key'...
newline ...
'                unlocked    = uint8(1);'...
newline ...
'                resp(1)     = uint8(hex2dec(''67''));'...
newline ...
'                resp(2)     = uint8(2);'...
newline ...
'                rlen        = uint8(2);'...
newline ...
'            else'...
newline ...
'                resp = nrc(SID, uint8(hex2dec(''35'')));  % invalidKey'...
newline ...
'                rlen = uint8(3);'...
newline ...
'            end'...
newline ...
'        else'...
newline ...
'            resp = nrc(SID, uint8(hex2dec(''12'')));'...
newline ...
'            rlen = uint8(3);'...
newline ...
'        end'...
newline ...
'      %% 0x2E WriteDataByIdentifier ─────────────────────────────────────'...
newline ...
'      case uint8(hex2dec(''2E''))'...
newline ...
'        if unlocked == 0'...
newline ...
'            resp = nrc(SID, uint8(hex2dec(''33'')));  % securityAccessDenied'...
newline ...
'            rlen = uint8(3);'...
newline ...
'        else'...
newline ...
'            did = uint16(req(2))*256 + uint16(req(3));'...
newline ...
'            val = bytes2float(req(4:7));'...
newline ...
'            if did == uint16(hex2dec(''F200''))'...
newline ...
'                ttc_w = val;'...
newline ...
'            elseif did == uint16(hex2dec(''F201''))'...
newline ...
'                ttc_l1 = val;'...
newline ...
'            elseif did == uint16(hex2dec(''F202''))'...
newline ...
'                kp_g = val;'...
newline ...
'            end'...
newline ...
'            resp(1) = uint8(hex2dec(''6E''));'...
newline ...
'            resp(2) = req(2); resp(3) = req(3);'...
newline ...
'            rlen    = uint8(3);'...
newline ...
'        end'...
newline ...
'      %% 0x14 ClearDiagnosticInformation ──────────────────────────────'...
newline ...
'      case uint8(hex2dec(''14''))'...
newline ...
'        dtc     = zeros(1,7,''uint8'');'...
newline ...
'        dtc_ctr = zeros(1,7,''uint16'');'...
newline ...
'        resp(1) = uint8(hex2dec(''54''));'...
newline ...
'        rlen    = uint8(1);'...
newline ...
'      %% 0x19 ReadDTCInformation ────────────────────────────────────────'...
newline ...
'      case uint8(hex2dec(''19''))'...
newline ...
'        % subfunção 0x02: reportDTCByStatusMask'...
newline ...
'        resp(1) = uint8(hex2dec(''59''));'...
newline ...
'        resp(2) = uint8(2);  % subFunction echo'...
newline ...
'        resp(3) = uint8(sum(dtc));  % número de DTCs ativos'...
newline ...
'        rlen    = uint8(3);'...
newline ...
'      %% 0x31 RoutineControl ───────────────────────────────────────────'...
newline ...
'      case uint8(hex2dec(''31''))'...
newline ...
'        routine_id = uint16(req(3))*256 + uint16(req(4));'...
newline ...
'        if routine_id == uint16(hex2dec(''0301''))   % enable/disable AEB'...
newline ...
'            aeb_en  = uint8(req(5));  % 0=disable 1=enable'...
newline ...
'            resp(1) = uint8(hex2dec(''71''));'...
newline ...
'            resp(2) = req(2); resp(3) = req(3); resp(4) = req(4);'...
newline ...
'            rlen    = uint8(4);'...
newline ...
'        elseif routine_id == uint16(hex2dec(''0302''))  % sensor self-test'...
newline ...
'            passed  = uint8(double(sum(dtc)==0));  % pass se sem DTCs'...
newline ...
'            resp(1) = uint8(hex2dec(''71''));'...
newline ...
'            resp(2) = req(2); resp(3) = req(3); resp(4) = req(4);'...
newline ...
'            resp(5) = passed;'...
newline ...
'            rlen    = uint8(5);'...
newline ...
'        else'...
newline ...
'            resp = nrc(SID, uint8(hex2dec(''31'')));'...
newline ...
'            rlen = uint8(3);'...
newline ...
'        end'...
newline ...
'      %% 0x3E TesterPresent ────────────────────────────────────────────'...
newline ...
'      case uint8(hex2dec(''3E''))'...
newline ...
'        s3      = 0.0;  % reset S3 timer'...
newline ...
'        resp(1) = uint8(hex2dec(''7E''));'...
newline ...
'        resp(2) = req(2);'...
newline ...
'        rlen    = uint8(2);'...
newline ...
'      otherwise'...
newline ...
'        resp = nrc(SID, uint8(hex2dec(''11'')));  % serviceNotSupported'...
newline ...
'        rlen = uint8(3);'...
newline ...
'    end  % switch SID'...
newline ...
'end  % req_valid'...
newline ...
'%% ── Saídas ──────────────────────────────────────────────────────────'...
newline ...
'resp_b1=double(resp(1)); resp_b2=double(resp(2));'...
newline ...
'resp_b3=double(resp(3)); resp_b4=double(resp(4));'...
newline ...
'resp_b5=double(resp(5)); resp_b6=double(resp(6));'...
newline ...
'resp_b7=double(resp(7)); resp_b8=double(resp(8));'...
newline ...
'resp_len     = double(rlen);'...
newline ...
'aeb_enabled  = double(aeb_en);'...
newline ...
'ttc_warn_cal = ttc_w;'...
newline ...
'ttc_l1_cal   = ttc_l1;'...
newline ...
'kp_cal       = kp_g;'...
newline ...
'dtc_active   = double(dtc);  % 1x7'...
newline ...
'dtc_count    = double(sum(dtc));'...
newline ...
'fault_lamp   = double(any(dtc));'...
newline ...
'session_state= double(sess);'...
newline ...
'sec_unlocked = double(unlocked);'...
newline ...
'end'...
newline ...
'%% ── Funções auxiliares ───────────────────────────────────────────────'...
newline ...
'function y = lfsr32(x)'...
newline ...
'%LFSR32  Galois LFSR 32 bits — polinomio 0x80200003'...
newline ...
'    POLY = uint32(hex2dec(''80200003''));'...
newline ...
'    if bitand(x, uint32(1))'...
newline ...
'        y = bitxor(bitshift(x,-1), POLY);'...
newline ...
'    else'...
newline ...
'        y = bitshift(x,-1);'...
newline ...
'    end'...
newline ...
'end'...
newline ...
'function key = compute_key(seed, xor_mask, add_const)'...
newline ...
'%COMPUTE_KEY  Derivação de chave: ROTL32(seed ^ mask, 7) + const'...
newline ...
'    masked   = bitxor(seed, xor_mask);'...
newline ...
'    rotated  = bitor(bitshift(masked, 7), bitshift(masked, -(32-7)));'...
newline ...
'    key      = rotated + add_const;  % wraps mod 2^32'...
newline ...
'end'...
newline ...
'function r = nrc(sid, nrc_code)'...
newline ...
'%NRC  Monta quadro de resposta negativa (NRC)'...
newline ...
'    r = zeros(1,8,''uint8'');'...
newline ...
'    r(1) = uint8(hex2dec(''7F''));'...
newline ...
'    r(2) = sid;'...
newline ...
'    r(3) = nrc_code;'...
newline ...
'end'...
newline ...
'function fb = float2bytes(f)'...
newline ...
'%FLOAT2BYTES  Converte float32 para 4 bytes (big-endian via typecast)'...
newline ...
'    fb = typecast(f, ''uint8'');'...
newline ...
'end'...
newline ...
'function f = bytes2float(b)'...
newline ...
'%BYTES2FLOAT  Converte 4 bytes para float32'...
newline ...
'    f = double(typecast(uint8(b(1:4)), ''single''));'...
newline ...
'end'...
];
end

%% ── Helper MATLAB: calcula chave para verificação do cenário ─────────────────
function key = uds_compute_key(seed)
    SECRET_XOR = uint32(hex2dec('A55A3CC3'));
    SECRET_ADD = uint32(hex2dec('12345678'));
    masked  = bitxor(seed, SECRET_XOR);
    rotated = bitor(bitshift(masked, 7), bitshift(masked, -(32-7)));
    key     = rotated + SECRET_ADD;
end
